version: '3.8'
services:
  epg:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - TZ=Europe/Minsk
    container_name: epg
    ports:
      - "3000:3000"

    volumes:
      - ./:/app
    tty: true
